/* CVS $Id: $ */
package jp.cormo.apagle.model.semantics;

import org.apache.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from resourcesactivitystreams2.ttl 
 * @author Auto-generated by schemagen on 05 10 2017 08:45 
 */
public class ActivityStreams2 {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static final Model M_MODEL = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "https://www.w3.org/ns/activitystreams#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}


    public static final Property HASHTAG = M_MODEL.createProperty( "https://www.w3.org/wiki/Activity_Streams_extensions#as:Hashtag_type" );

    public static final Property SENSITIVE = M_MODEL.createProperty( "https://www.w3.org/wiki/Activity_Streams_extensions#as:Sensitive" );

    public static final Property MANUALLY_APPROVES_FOLLOWERS = M_MODEL.createProperty( "https://www.w3.org/wiki/Activity_Streams_extensions#as:manuallyApprovesFollowers" );

    public static final Property PUBLIC_KEY = M_MODEL.createProperty( "https://web-payments.org/vocabs/security#publicKey" );

    public static final Property PUBLIC_KEY_PEM = M_MODEL.createProperty( "https://web-payments.org/vocabs/security#publicKeyPem" );

    public static final Property OWNER = M_MODEL.createProperty( "https://web-payments.org/vocabs/security#owner" );


    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );
    
    /** <p>Specifies the accuracy around the point established by the longitude and latitude</p> */
    public static final Property ACCURACY = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#accuracy" );
    
    /** <p>Subproperty of as:attributedTo that identifies the primary actor</p> */
    public static final Property ACTOR = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#actor" );
    
    /** <p>The altitude of a place</p> */
    public static final Property ALTITUDE = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#altitude" );
    
    /** <p>Describes a possible inclusive answer or option for a question.</p> */
    public static final Property ANY_OF = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#anyOf" );
    
    public static final Property ATTACHMENT = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#attachment" );
    
    public static final Property ATTACHMENTS = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#attachments" );
    
    /** <p>Identifies an entity to which an object is attributed</p> */
    public static final Property ATTRIBUTED_TO = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#attributedTo" );
    
    public static final Property AUDIENCE = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#audience" );
    
    /** <p>Identifies the author of an object. Deprecated. Use as:attributedTo instead</p> */
    public static final Property AUTHOR = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#author" );
    
    public static final Property BCC = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#bcc" );
    
    public static final Property BTO = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#bto" );
    
    public static final Property CC = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#cc" );
    
    /** <p>The content of the object.</p> */
    public static final Property CONTENT = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#content" );
    
    /** <p>Specifies the context within which an object exists or an activity was performed</p> */
    public static final Property CONTEXT = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#context" );
    
    public static final Property CURRENT = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#current" );
    
    /** <p>Specifies the date and time the object was deleted</p> */
    public static final Property DELETED = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#deleted" );
    
    /** <p>On a Profile object, describes the object described by the profile</p> */
    public static final Property DESCRIBES = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#describes" );
    
    public static final Property DOWNSTREAM_DUPLICATES = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#downstreamDuplicates" );
    
    /** <p>The duration of the object</p> */
    public static final Property DURATION = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#duration" );
    
    /** <p>The ending time of the object</p> */
    public static final Property END_TIME = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#endTime" );
    
    public static final Property FIRST = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#first" );
    
    /** <p>On a Tombstone object, describes the former type of the deleted object</p> */
    public static final Property FORMER_TYPE = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#formerType" );
    
    public static final Property GENERATOR = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#generator" );
    
    /** <p>The display height expressed as device independent pixels</p> */
    public static final Property HEIGHT = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#height" );
    
    /** <p>The target URI of the Link</p> */
    public static final Property HREF = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#href" );
    
    /** <p>A hint about the language of the referenced resource</p> */
    public static final Property HREFLANG = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#hreflang" );
    
    public static final Property ICON = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#icon" );
    
    public static final Property ID = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#id" );
    
    public static final Property IMAGE = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#image" );
    
    public static final Property IN_REPLY_TO = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#inReplyTo" );
    
    /** <p>Indentifies an object used (or to be used) to complete an activity</p> */
    public static final Property INSTRUMENT = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#instrument" );
    
    public static final Property ITEMS = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#items" );
    
    public static final Property LAST = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#last" );
    
    /** <p>The latitude</p> */
    public static final Property LATITUDE = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#latitude" );
    
    public static final Property LOCATION = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#location" );
    
    /** <p>The longitude</p> */
    public static final Property LONGITUDE = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#longitude" );
    
    /** <p>The MIME Media Type</p> */
    public static final Property MEDIA_TYPE = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#mediaType" );
    
    public static final Property NAME = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#name" );
    
    public static final Property NEXT = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#next" );
    
    public static final Property OBJECT = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#object" );
    
    public static final Property OBJECT_TYPE = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#objectType" );
    
    /** <p>Describes a possible exclusive answer or option for a question.</p> */
    public static final Property ONE_OF = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#oneOf" );
    
    /** <p>For certain activities, specifies the entity from which the action is directed.</p> */
    public static final Property ORIGIN = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#origin" );
    
    public static final Property PART_OF = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#partOf" );
    
    public static final Property PREV = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#prev" );
    
    public static final Property PREVIEW = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#preview" );
    
    public static final Property PROVIDER = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#provider" );
    
    /** <p>Specifies the date and time the object was published</p> */
    public static final Property PUBLISHED = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#published" );
    
    /** <p>Specifies a radius around the point established by the longitude and latitude</p> */
    public static final Property RADIUS = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#radius" );
    
    /** <p>A numeric rating (&gt;= 0.0, &lt;= 5.0) for the object</p> */
    public static final Property RATING = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#rating" );
    
    /** <p>The RFC 5988 or HTML5 Link Relation associated with the Link</p> */
    public static final Property REL = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#rel" );
    
    /** <p>On a Relationship object, describes the type of relationship</p> */
    public static final Property RELATIONSHIP = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#relationship" );
    
    public static final Property REPLIES = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#replies" );
    
    public static final Property RESULT = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#result" );
    
    /** <p>In a strictly ordered logical collection, specifies the index position of 
     *  the first item in the items list</p>
     */
    public static final Property START_INDEX = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#startIndex" );
    
    /** <p>The starting time of the object</p> */
    public static final Property START_TIME = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#startTime" );
    
    /** <p>On a Relationship object, identifies the subject. e.g. when saying "John is 
     *  connected to Sally", 'subject' refers to 'John'</p>
     */
    public static final Property SUBJECT = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#subject" );
    
    /** <p>A short summary of the object</p> */
    public static final Property SUMMARY = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#summary" );
    
    public static final Property TAG = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#tag" );
    
    public static final Property TAGS = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#tags" );
    
    public static final Property TARGET = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#target" );
    
    public static final Property TO = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#to" );
    
    /** <p>The total number of items in a logical collection</p> */
    public static final Property TOTAL_ITEMS = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#totalItems" );
    
    /** <p>Identifies the unit of measurement used by the radius, altitude and accuracy 
     *  properties. The value can be expressed either as one of a set of predefined 
     *  units or as a well-known common URI that identifies units.</p>
     */
    public static final Property UNITS = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#units" );
    
    /** <p>Specifies when the object was last updated</p> */
    public static final Property UPDATED = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#updated" );
    
    public static final Property UPSTREAM_DUPLICATES = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#upstreamDuplicates" );
    
    /** <p>Specifies a link to a specific representation of the Object</p> */
    public static final Property URL = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#url" );
    
    public static final Property VERB = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#verb" );
    
    /** <p>Specifies the preferred display width of the content, expressed in terms of 
     *  device independent pixels.</p>
     */
    public static final Property WIDTH = M_MODEL.createProperty( "https://www.w3.org/ns/activitystreams#width" );
    
    /** <p>Actor accepts the Object</p> */
    public static final Resource ACCEPT = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Accept" );
    
    /** <p>An Object representing some form of Action that has been taken</p> */
    public static final Resource ACTIVITY = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Activity" );
    
    /** <p>To Add an Object or Link to Something</p> */
    public static final Resource ADD = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Add" );
    
    /** <p>Actor announces the object to the target</p> */
    public static final Resource ANNOUNCE = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Announce" );
    
    /** <p>Represents a software application of any sort</p> */
    public static final Resource APPLICATION = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Application" );
    
    /** <p>To Arrive Somewhere (can be used, for instance, to indicate that a particular 
     *  entity is currently located somewhere, e.g. a "check-in")</p>
     */
    public static final Resource ARRIVE = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Arrive" );
    
    /** <p>A written work. Typically several paragraphs long. For example, a blog post 
     *  or a news article.</p>
     */
    public static final Resource ARTICLE = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Article" );
    
    /** <p>An audio file</p> */
    public static final Resource AUDIO = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Audio" );
    
    public static final Resource BLOCK = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Block" );
    
    /** <p>An ordered or unordered collection of Objects or Links</p> */
    public static final Resource COLLECTION = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Collection" );
    
    /** <p>A subset of items from a Collection</p> */
    public static final Resource COLLECTION_PAGE = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#CollectionPage" );
    
    /** <p>To Create Something</p> */
    public static final Resource CREATE = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Create" );
    
    /** <p>To Delete Something</p> */
    public static final Resource DELETE = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Delete" );
    
    /** <p>The actor dislikes the object</p> */
    public static final Resource DISLIKE = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Dislike" );
    
    /** <p>Represents a digital document/file of any sort</p> */
    public static final Resource DOCUMENT = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Document" );
    
    /** <p>An Event of any kind</p> */
    public static final Resource EVENT = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Event" );
    
    /** <p>To flag something (e.g. flag as inappropriate, flag as spam, etc)</p> */
    public static final Resource FLAG = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Flag" );
    
    /** <p>To Express Interest in Something</p> */
    public static final Resource FOLLOW = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Follow" );
    
    /** <p>A Group of any kind.</p> */
    public static final Resource GROUP = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Group" );
    
    /** <p>Actor is ignoring the Object</p> */
    public static final Resource IGNORE = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Ignore" );
    
    /** <p>An Image file</p> */
    public static final Resource IMAGE_CLASS = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Image" );
    
    /** <p>An Activity that has no direct object</p> */
    public static final Resource INTRANSITIVE_ACTIVITY = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#IntransitiveActivity" );
    
    /** <p>To invite someone or something to something</p> */
    public static final Resource INVITE = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Invite" );
    
    /** <p>To Join Something</p> */
    public static final Resource JOIN = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Join" );
    
    /** <p>To Leave Something</p> */
    public static final Resource LEAVE = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Leave" );
    
    /** <p>To Like Something</p> */
    public static final Resource LIKE = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Like" );
    
    /** <p>Represents a qualified reference to another resource. Patterned after the 
     *  RFC5988 Web Linking Model</p>
     */
    public static final Resource LINK = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Link" );
    
    /** <p>The actor listened to the object</p> */
    public static final Resource LISTEN = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Listen" );
    
    /** <p>A specialized Link that represents an @mention</p> */
    public static final Resource MENTION = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Mention" );
    
    /** <p>The actor is moving the object. The target specifies where the object is moving 
     *  to. The origin specifies where the object is moving from.</p>
     */
    public static final Resource MOVE = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Move" );
    
    /** <p>A Short note, typically less than a single paragraph. A "tweet" is an example, 
     *  or a "status update"</p>
     */
    public static final Resource NOTE = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Note" );
    
    public static final Resource OBJECT_CLASS = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Object" );
    
    /** <p>To Offer something to someone or something</p> */
    public static final Resource OFFER = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Offer" );
    
    /** <p>A variation of Collection in which items are strictly ordered</p> */
    public static final Resource ORDERED_COLLECTION = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#OrderedCollection" );
    
    /** <p>An ordered subset of items from an OrderedCollection</p> */
    public static final Resource ORDERED_COLLECTION_PAGE = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#OrderedCollectionPage" );
    
    /** <p>A rdf:List variant for Objects and Links</p> */
    public static final Resource ORDERED_ITEMS = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#OrderedItems" );
    
    /** <p>An Organization</p> */
    public static final Resource ORGANIZATION = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Organization" );
    
    /** <p>A Web Page</p> */
    public static final Resource PAGE = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Page" );
    
    /** <p>A Person</p> */
    public static final Resource PERSON = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Person" );
    
    /** <p>A physical or logical location</p> */
    public static final Resource PLACE = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Place" );
    
    /** <p>A Profile Document</p> */
    public static final Resource PROFILE = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Profile" );
    
    /** <p>A question of any sort.</p> */
    public static final Resource QUESTION = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Question" );
    
    /** <p>The actor read the object</p> */
    public static final Resource READ = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Read" );
    
    /** <p>Actor rejects the Object</p> */
    public static final Resource REJECT = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Reject" );
    
    /** <p>Represents a Social Graph relationship between two Individuals (indicated 
     *  by the 'a' and 'b' properties)</p>
     */
    public static final Resource RELATIONSHIP_CLASS = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Relationship" );
    
    /** <p>To Remove Something</p> */
    public static final Resource REMOVE = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Remove" );
    
    /** <p>A service provided by some entity</p> */
    public static final Resource SERVICE = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Service" );
    
    /** <p>Actor tentatively accepts the Object</p> */
    public static final Resource TENTATIVE_ACCEPT = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#TentativeAccept" );
    
    /** <p>Actor tentatively rejects the object</p> */
    public static final Resource TENTATIVE_REJECT = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#TentativeReject" );
    
    /** <p>A placeholder for a deleted object</p> */
    public static final Resource TOMBSTONE = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Tombstone" );
    
    /** <p>The actor is traveling to the target. The origin specifies where the actor 
     *  is traveling from.</p>
     */
    public static final Resource TRAVEL = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Travel" );
    
    /** <p>To Undo Something. This would typically be used to indicate that a previous 
     *  Activity has been undone.</p>
     */
    public static final Resource UNDO = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Undo" );
    
    /** <p>To Update/Modify Something</p> */
    public static final Resource UPDATE = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Update" );
    
    /** <p>A Video document of any kind.</p> */
    public static final Resource VIDEO = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#Video" );
    
    /** <p>The actor viewed the object</p> */
    public static final Resource VIEW = M_MODEL.createResource( "https://www.w3.org/ns/activitystreams#View" );
    
    public static final Resource NIL = M_MODEL.createResource( "http://www.w3.org/1999/02/22-rdf-syntax-ns#nil" );
    
}
